version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CONVERSION_TIMEOUT=${CONVERSION_TIMEOUT:-300}  # Таймаут в секундах, по умолчанию 5 минут
    volumes:
      - /tmp/telegram_video_converter:/tmp/telegram_video_converter
    devices:
      - /dev/nvidia0:/dev/nvidia0
    runtime: nvidia
    restart: unless-stopped